FROM python:3.10-slim-bullseye

WORKDIR /code

COPY ./api /code
RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y gcc
RUN pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install -r requirements.txt

