FROM python:3.9-slim-buster

WORKDIR /code

COPY ./api /code
RUN apt-get update
RUN apt-get install -y vim less
RUN pip install --upgrade pip && pip install --upgrade setuptools && pip install -r requirements.txt

